export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const LOAD_APP_DATA = 'LOAD_APP_DATA_START';
export const LOAD_APP_DATA_SUCCESS = 'LOAD_APP_DATA_SUCCESS';
export const LOAD_APP_DATA_ERROR = 'LOAD_APP_DATA_ERROR';
