export const ActionTypes = {
  BEGIN_API_CALL: 'api/BEGIN_API_CALL',
  API_CALL_ERROR: 'api/API_CALL_ERROR',

  APP: {
    LOAD_APP_DATA_START: 'appdata/LOAD_APP_DATA_START',
    LOAD_APP_DATA_SUCCESS: 'appdata/LOAD_APP_DATA_SUCCESS',
    LOAD_APP_DATA_ERROR: 'appdata/LOAD_APP_DATA_ERROR'
  },
  // Auth
  LOGIN: {
    LOGIN_START: 'AUTH/LOGIN_START',
    LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
    LOGIN_ERROR: 'AUTH/LOGIN_ERROR'
  },
  LOGOUT: 'AUTH/LOGOUT'
};
