export var ActionTypes = {
  BEGIN_API_CALL: 'api/BEGIN_API_CALL',
  API_CALL_ERROR: 'api/API_CALL_ERROR',

  LOAD_APP_DATA_START: 'appdata/LOAD_APP_DATA_START',
  LOAD_APP_DATA_SUCCESS: 'appdata/LOAD_APP_DATA_SUCCESS'
};
